% script to obtain the measures for all the bins concerning the
% Accent perception dataser. 29 ERPsets


 % N1 Onset 95-155 ms:
ALLERP = pop_geterpvalues( ALLERP, [95 155],  [1:27], [1:62, 65] , 'Baseline', 'pre', 'Binlabel', 'on', 'Erpsets',  1:29, 'FileFormat', 'long',...
 'Filename', 'C:\Users\Pell Lab\Documents\MATLAB\accent_perception\14.statistics\N1Onset95-155.xls', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'meanbl', 'Resolution',  2 );

 % P2 Onset 200-260 ms:
ALLERP = pop_geterpvalues( ALLERP, [200 260],  [1:27], [1:62,65] , 'Baseline', 'pre', 'Binlabel', 'on', 'Erpsets',  1:29, 'FileFormat', 'long',...
 'Filename', 'C:\Users\Pell Lab\Documents\MATLAB\accent_perception\14.statistics\P2Onset200-260.xls', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'meanbl', 'Resolution',  2 );


 % N400 Adj 300-500 ms :
ALLERP = pop_geterpvalues( ALLERP, [300 500],  [55:81], [1:62,65] , 'Baseline', 'pre', 'Binlabel', 'on', 'Erpsets',  1:29, 'FileFormat', 'long',...
 'Filename', 'C:\Users\Pell Lab\Documents\MATLAB\accent_perception\14.statistics\N400_ADJ_300-500.xls', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'meanbl', 'Resolution',  2 );


% LPP ADJ 500-800 ms:
ALLERP = pop_geterpvalues( ALLERP, [500 800],  [55:81], [1:62,65] , 'Baseline', 'pre', 'Binlabel', 'on', 'Erpsets',  1:29, 'FileFormat', 'long',...
 'Filename', 'C:\Users\Pell Lab\Documents\MATLAB\accent_perception\14.statistics\LPP_ADJ_500-800.xls', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'meanbl', 'Resolution',  2 );


% EPN ADJ 200-400 ms:
ALLERP = pop_geterpvalues( ALLERP, [200 400],  [55:81], [1:62,65] , 'Baseline', 'pre', 'Binlabel', 'on', 'Erpsets',  1:29, 'FileFormat', 'long',...
 'Filename', 'C:\Users\Pell Lab\Documents\MATLAB\accent_perception\14.statistics\EPN_ADJ_200-400.xls', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'meanbl', 'Resolution',  2 );

  % LPP Onset 500-800 ms:
ALLERP = pop_geterpvalues( ALLERP, [500 800],  [1:27], [1:62,65] , 'Baseline', 'pre', 'Binlabel', 'on', 'Erpsets',  1:29, 'FileFormat', 'long',...
 'Filename', 'C:\Users\Pell Lab\Documents\MATLAB\accent_perception\14.statistics\LPP_Onset_500-800.xls', 'Fracreplace', 'NaN', 'InterpFactor',  1,...
 'Measure', 'meanbl', 'Resolution',  2 );

